[project]
name = "jdc-code-brewsandbytes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.1",
    "geopandas>=1.0.1",
    "marimo>=0.11.17",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
]
