version: '3.8'

services:
  db-app:
    image: postgres:15
    container_name: brews_and_bytes_app_db
    environment:
      POSTGRES_DB: brews_and_bytes_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
      - ./brews_and_bytes_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
      - ./mock_users.csv:/docker-entrypoint-initdb.d/data/mock_users.csv
      - ./mock_contacts.csv:/docker-entrypoint-initdb.d/data/mock_contacts.csv
      - ./mock_signups.csv:/docker-entrypoint-initdb.d/data/mock_signups.csv
      - ./mock_subscribers.csv:/docker-entrypoint-initdb.d/data/mock_subscribers.csv
      - ./mock_coffee_shops.csv:/docker-entrypoint-initdb.d/data/mock_coffee_shops.csv
      - ./load_mock_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
    networks:
      - brews_and_bytes_network

  adminer-app:
    image: adminer
    container_name: brews_and_bytes_app_adminer
    ports:
      - "8081:8080"
    networks:
      - brews_and_bytes_network
    environment:
      ADMINER_DEFAULT_SERVER: db-app
    depends_on:
      - db-app

volumes:
  postgres_app_data:

networks:
  brews_and_bytes_network:
    driver: bridge